---
title: "test"
author: "Anna Calle"
date: "5/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set-Up for Downloading Data Using Google Drive File Stream
```{r}
# Create a Root to Extract Files 
if(Sys.info()["sysname"] == "Windows"){ #If operating system is "Windows" use G: Drive
  team_path <- "G:/"
} else { # If it is not (i.e. Mac), use the Google Drive File Stream
  team_path <- "/Volumes/GoogleDrive/"
}

#Create the Full File Path
path <- paste0(team_path, "Shared drives/ESM232/Data")

```

Read in data
```{r}
#generate a list of input rasters 
solar_rasters <- list.files(paste0(path, "/tair_flx_ccsm3a2bcsd/") , 
                           pattern = "*.tif$")

#create a raster stack from the input raster files 
solar_stack <- raster::stack(paste0(paste0(path, "/tair_flx_ccsm3a2bcsd/"), solar_rasters))

# rename bands
names(solar_stack) <- c("jan", "feb", "mar", "apr", "may", "jun", 
                        "jul", "aug", "sep", "oct", "nov", "dec")

# plot
plot(solar_stack)
```








