---
title: "property_tax"
author: "Yingfei Jiang"
date: "5/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(here)
library(paletteer)
```

```{r}
# Create a Root to Extract Files 
if(Sys.info()["sysname"] == "Windows"){ # If operating system is "Windows" use G: Drive
  team_path <- "G:/"
} else { # If it is not (i.e. Mac), use the Google Drive File Stream
  team_path <- "/Volumes/GoogleDrive/"
}

# Create the Full File Path
path <- paste0(team_path, "Shared drives/ESM232/Data")

```

```{r}
#Read in property tax shape file
raw_df <- read_sf(dsn = paste0(path, "/PropertyTaxes"), layer = "BOE_PropertyTaxes")

```

```{r}
# Assign projection: NAD83
NAD83 <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83
+units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 "
```

```{r}
land_value_2019 <- raw_df %>% 
  select(strCounty, ABBREV, FIPS, intYrTo, intLand) %>% 
  filter(intYrTo == 2020) %>% 
  mutate(area = st_area(.)) %>% 
  mutate(unitLand = as.numeric(intLand/area))

# make the CRS consistent
land_value_2019 <- st_transform(land_value_2019, NAD83)
```

```{r}
ggplot(land_value_2019) +
  geom_sf(aes(fill = unitLand), color = NA) +
  scale_fill_paletteer_c("ggthemes::Orange") +
  scale_size(guide = "none") + #Removing size legend
  labs(fill = "Land Value ($/m^2)")
  
```

```{r}
#creating a data.frame storing the average solar output

solar_energy_simple <- county_energy_sp %>% 
  select(-geom) %>% 
  mutate(strCounty = str_to_title(str_remove(ID, "california,"))) %>% 
  select(-ID, -score)


df_LCOE <- full_join(solar_energy_simple, land_value_2019) %>% 
  select(-ABBREV, -FIPS, -intYrTo, -intLand, -area)
```

```{r}
source("LCOE.R")

df_LCOE <- df_LCOE %>% 
  mutate(LCOE = LCOE(gen = energy_output, size = 20000, total_om = 8.12, instant_cost = 1585, installed_cost = 1861, land_cost = unitLand)) %>% 
  st_as_sf()

#final_LCOE <- mapply(LCOE, gen = df_LCOE$energy_output, MoreArgs = list(size = 20000, total_om = 8.12, #instant_cost = 1742, installed_cost = 1861))
```

```{r}
ggplot(df_LCOE) +
  geom_sf(aes(fill = LCOE), color = NA) +
  scale_fill_paletteer_c("ggthemes::Orange") +
  scale_size(guide = "none") + #Removing size legend
  labs(fill = "LCOE ($/MWh)")
  
```

