---
title: "Solar Insolation"
author: "AnnaClaire Marley"
date: "5/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# load packages
library(raster)
library(maps)
library(sf)
library(tidyverse)
```

### Calculate projected solar energy output in CA given solar radiation projections


Net surface radiation 

* Model: CCSM3
* Emission scenario: A2
* Year: 2050


```{r}
# Create a Root to Extract Files 
if(Sys.info()["sysname"] == "Windows"){ #If operating system is "Windows" use G: Drive
  team_path <- "G:/"
} else { # If it is not (i.e. Mac), use the Google Drive File Stream
  team_path <- "/Volumes/GoogleDrive/"
}

#Create the Full File Path
path <- paste0(team_path, "Shared drives/ESM232/Data")

```


```{r}

#generate a list of input rasters ("solar_rasters")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
solar_rasters <- list.files(paste0(path,"/nrad_flx_ccsm3a2bcsd") , 
                           pattern = "*.tif$")

#create a raster stack from the input raster files 
solar_stack <- raster::stack(paste0(paste0(path,"/nrad_flx_ccsm3a2bcsd/"), solar_rasters))

# rename bands
names(solar_stack) <- c("jan", "feb", "mar", "apr", "may", "jun", 
                        "jul", "aug", "sep", "oct", "nov", "dec")

# plot
plot(solar_stack)
```


Crop and mask rasters to California 

```{r}
# grab US states from maps package
california <- st_as_sf(maps::map("state", plot = FALSE, fill = TRUE)) %>% 
  filter(ID == "california")

# make the polygon the same CRS as rasters
california_project <- st_transform(california, crs(solar_stack))

```

```{r}
# function to crop and mask all rasters to california

# raster: the raster files
# polygon: california_project
ca_crop_mask = function(raster, polygon){
  
  crop <- crop(raster, polygon)
  mask <- mask(crop, polygon)
  
  return(mask)
}
```


```{r}
# crop and mask to ca
solar_stack_mask <- ca_crop_mask(solar_stack, california_project)

# plot
plot(solar_stack_mask)

```


Energy output equation
```{r}

# function to calculate energy output for each month
energy_output = function(raster){
  
  output = raster * 4.5
  
  return(output)
  
}

```

```{r}
# test energy output

solar_stack_energy <- energy_output(solar_stack_mask)

plot(solar_stack_mask)
plot(solar_stack_energy)

```

