#' Land suitability by county
#' 
#' Ranks counties in California by the amount of suitable land available for solar energy generation
#'
#' @param suitable_raster raster file of suitable sites for solar energy in CA generated by the suitable_land function
#' @param year year correponding to suitable_raster
#'
#' @return returns a list with four elements: suitable_raster_map, suitable_pct_map, suitable_rank_map, counties_scores_df

suitable_land_counties <- function(suitable_raster, year) {
  
  ### RASTER MAP WITH COUNTY BOUNDARIES ###
  # Read CA counties file
  counties_proj <- read_sf(dsn = "generated_files/",
                           layer = "counties_proj")
  
  # Read CA file
  CA_proj <- read_sf(dsn = "generated_files/",
                     layer = "counties_proj")
  
  # Get paletteer colors
  colors <- paletteer_c("ggthemes::Temperature Diverging", n = 2)
  
  # Convert suitable raster to data frame
  suitable_df <- as.data.frame(suitable_raster, xy = TRUE)
  
  # Map
  suitable_raster_map <- ggplot() +
    geom_raster(data = suitable_df,
                mapping = aes(x = x, y = y,  fill = factor(layer))) +
    scale_fill_manual(name = "",
                      values=c(colors[1], colors[2]),
                      labels=c("Excluded", "Suitable", "")) +
    geom_sf(data = counties_proj,
            fill = "transparent",
            color = "gray30", 
            size = 0.1) +
    theme_minimal() +
    coord_sf(datum=NA) +
    labs(x = "", y = "", title = paste0("Suitable Land in CA by County in ", year)) +
    annotation_scale(location = "bl", style = "ticks") # scale bar
  
  
  ### CALCULATING % OF SUITABLE LAND ###
  # Add suitable area column
  counties_proj$suitable_area <- NA
  
  # Add suitable area percentage column
  counties_proj$suitable_pct <- NA
  
  # Loop through each county
  for (i in 1:nrow(counties_proj)) {
    
    # Select ith county
    county <- counties_proj[i, ]
    
    # Crop
    suitable_cropped <- crop(suitable_raster, county)
    
    # Mask
    suitable_masked <- mask(suitable_cropped, county, progress = 'text')
    
    # Count suitable cells
    count <-  freq(suitable_masked, value = 1)
    
    # Calculate area (number of cells * cell resolution)
    counties_proj$suitable_area[i] <- count * 1000 * 1000
    
    # Calculate area percentage
    counties_proj$suitable_pct[i] <- counties_proj$suitable_area[i] / counties_proj$area[i] * 100
  }
  
  ### MAP OF % OF SUITABLE LAND ###
  # Map
  suitable_pct_map <- ggplot() +
    geom_sf(
      data = counties_proj,
      color = "gray30",
      size = 0.1,
      aes(fill = counties_proj$suitable_pct)) +
    scale_fill_paletteer_c("ggthemes::Temperature Diverging",
                           name = "Suitable Land (%)") +
    theme_minimal() +
    coord_sf(datum = NA) +
    labs(x = "", y = "", title = paste0("Suitable Land in CA by County in ", year)) +
    annotation_scale(location = "bl", style = "ticks") # scale bar
  
  ### CALCULATING RANKINGS (SCORES) ###
  # Create scores column
  counties_proj$score_land <- NA
  
  # Rank counties by % of suitable land
  counties_proj$score_land[order(counties_proj$suitable_pct)] <-
    1:nrow(counties_proj)
  
  # Rank dataframe
  counties_scores_df <- as.data.frame(counties_proj) %>%
    dplyr::select(County, score_land )
  
  ### MAP RANKINGS ###
  suitable_rank_map <- ggplot() +
    geom_sf(data = counties_proj,
            color = "gray30", 
            size = 0.1,
            aes(fill = counties_proj$score_land)) +
    scale_fill_paletteer_c("ggthemes::Temperature Diverging",
                           name = "Rank") + 
    theme_minimal() +
    coord_sf(datum=NA) +
    labs(x = "", y = "", title = paste0("Suitable Land in CA by County in ", year)) +
    annotation_scale(location = "bl", style = "ticks") # scale bar
  
  # Return list with rank dataframe, raster map, and % suitable land map
  return(list(suitable_raster_map,
              suitable_pct_map,
              suitable_rank_map,
              counties_scores_df))
  
}

